DELETE http://localhost:3001/api/persons/6669d23ae67dd4099597ea00

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ragnar Lobthdrok",
    "number": "040-223123"
}

###

GET http://localhost:3001/api/persons/