DELETE http://localhost:3001/api/persons/66686f7ce5f9ee1c147ccb7

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ragnar Lobthdrok",
    "number": "040-223123"
}

###

GET http://localhost:3001/api/persons/

###

GET http://localhost:3001/api/persons/2

###

PUT http://localhost:3001/api/persons/
Content-Type: : application/json

{
    "name": "Ragnar Lobthdrok",
    "number": "040-23231212"
}